### ISSUE TITLE
API for adding comments to toml objects

### ISSUE THREAD

**Issue by A248** [xtomlj/xtomlj#2]
It would be very useful to be able to write comments. To do this, adding comments to the API is a first step.

**API Layout**
I would suggest a `List<Comment>` to be added as a property of TomlTable. `Comment` would be a wrapper around a String and possibly a comment position.

**Related**
The next step would be to write these comments in the `toToml()` methods. Comment writing would not be too difficult to implement.

Comment parsing may be more complicated (and is it even spec-compliant? I know the yaml spec says not to read comments) so you may want to leave that to a further time. I personally don't need it for my use-case but others may find it useful.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I don't think the Toml spec says much about comments.

In general, comments are only intended to be read by a human and should not have any meaning on program code / data definitions.
(E.g. it would not make sense to derive a data type from a comment)

TOML only supports line comments (starting with "#" to the end of the line).

Since it would not be trivial to derive a position (row, column) from a data structure, I would rather assign the comments to values.

**Examples**
`[database] # Comment for database`
`server = "192.168.1.1" # Comment for server`
`ports = [ 8001, # Comment for ports[0]`
`8001, 8002 ] # Comment for ports`

The most common use case for reading comments, on the other hand, would be to just preserve them.

**Comment by A248** [comment]
Comments on keys and values is what I imagined. Do you think it would be possible to have comments *on top of* keys instead of next to them? For example:

```toml
# Comment for database
# Another comment for database
[database]  
# Comment for server
server = "192.168.1.1" 
```

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
> Do you think it would be possible to have comments on top of keys instead of next to them?

Yes, I would add something like an additional "style" value.

```java
enum Style {
  BEFORE_LINE,
  IN_LINE,
  AFTER_LINE
}
```

```toml
# Comment for database (BEFORE_LINE)
# Another comment for database (BEFORE_LINE)
[database] # Database (INLINE)
# Comment for server (BEFORE_LINE)
server = "192.168.1.1" 
```
